### ISSUE TITLE
Error when running FastClipV3 on two H100 Nodes

### ISSUE THREAD

**Issue by mmderakhshani** [Optimization-AI/fast_clip#1]
Hi,

Thanks for sharing the source code of your paper. I was planning to run your code locally on two H100 nodes. However, I could not be able to run it: 

Following is my sbatch:
```
#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --time=2-00:00:00
#SBATCH --mem=700G
#SBATCH --nodes=1
#SBATCH --gpus=4
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=16
#SBATCH --wait-all-nodes=1
#SBATCH --job-name=fastclipv3
#SBATCH --output=%x_%j_logs.log
#SBATCH --error=%x_%j_errors.log

module load 2023
echo start at `date`
export PATH=$HOME/.conda/envs/fastclip/bin/:$PATH
export OMP_NUM_THREADS=1

source ~/.bashrc
# conda activate fastclip

master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
export MASTER_PORT=12805

export PYTHONPATH="$PYTHONPATH:$PWD/src"
export HUGGINGFACE_HUB_CACHE='./checkpoints/huggingface'


srun python -u src/training/main.py \
    --save-frequency 1 \
    --train-data 'REMOTE_HOST:PATH_TO_DATASETS/ConceptualCaptions/train_shards/{00000..00319}.tar' \
    --train-num-samples 2723840 --data_size 3318333 \
    --warmup 10000 \
    --batch-size 256 \
    --epochs 37 \
    --workers 6 \
    --model RN50 \
    --name medium_fastclipv3 \
    --seed 2024 \
    --profile \
    --wd 0.1 \
    --local-loss \
    --fastclip --multiply_tau --temperature_scheme global_learnable \
    --lr 1e-3 --lr_tau 2e-4 --lr_tau_scheduler step_thresh --rho 6.5 \
    --gamma 0.2 --gamma_schedule cosine --gamma_decay_epochs 18
```

However, I am getting the following error:

```
Traceback (most recent call last):
  File "/gpfs/home2/mmahdid/fast_clip/src/training/main.py", line 611, in <module>
    main(sys.argv[1:])
  File "/gpfs/home2/mmahdid/fast_clip/src/training/main.py", line 304, in main
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[device], **ddp_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 798, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/distributed/utils.py", line 263, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer
Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x14731f1cbd87 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x589518e (0x14735aec318e in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x360 (0x14735aebd9a0 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x14735aebdce2 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #4: c10d::TCPStore::get(std::string const&) + 0xa1 (0x14735aebeb11 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14735ae73f81 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14735ae73f81 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14735ae73f81 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #8: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xa9 (0x1473203474e9 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #9: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, std::vector<c10::Device, std::allocator<c10::Device> > const&, c10d::OpType, int, bool) + 0x22b (0x14732034e4db in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #10: c10d::ProcessGroupNCCL::allgather(std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > >&, std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllgatherOptions const&) + 0xb5c (0x1473203648dc in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0x583a31d (0x14735ae6831d in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x5844218 (0x14735ae72218 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x4e893cc (0x14735a4b73cc in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x1a08a88 (0x147357036a88 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x584ba33 (0x14735ae79a33 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x5856e1f (0x14735ae84e1f in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #17: c10d::verify_params_across_processes(c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::optional<std::weak_ptr<c10d::Logger> > const&) + 0x26f (0x14735aeeb48f in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0xc62071 (0x14736d6ee071 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #19: <unknown function> + 0x416284 (0x14736cea2284 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #20: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x528767]
frame #21: _PyObject_MakeTpCall + 0x26c (0x5041ac in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #22: _PyEval_EvalFrameDefault + 0x6a7 (0x5116e7 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #23: _PyFunction_Vectorcall + 0x173 (0x538cc3 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #24: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5400d2]
frame #25: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5045ac]
frame #26: PyObject_Call + 0xbd (0x542b7d in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #27: _PyEval_EvalFrameDefault + 0x47a9 (0x5157e9 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #28: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5cbeda]
frame #29: PyEval_EvalCode + 0x9f (0x5cb5af in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #30: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5ec6a7]
frame #31: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5e8240]
frame #32: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5fd192]
frame #33: _PyRun_SimpleFileObject + 0x19f (0x5fc55f in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #34: _PyRun_AnyFileObject + 0x43 (0x5fc283 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #35: Py_RunMain + 0x2ee (0x5f6efe in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #36: Py_BytesMain + 0x39 (0x5bbc79 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #37: __libc_start_main + 0xe5 (0x14737f809d85 in /lib64/libc.so.6)
frame #38: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5bbac3]
. This may indicate a possible application crash on rank 0 or a network set up issue.
[rank1]:[2024-07-09 10:12:38,066] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[rank1]:[2024-07-09 10:12:38,066] torch._dynamo.utils: [INFO] Function, Runtimes (s)
Traceback (most recent call last):
  File "/gpfs/home2/mmahdid/fast_clip/src/training/main.py", line 611, in <module>
    main(sys.argv[1:])
  File "/gpfs/home2/mmahdid/fast_clip/src/training/main.py", line 304, in main
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[device], **ddp_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 798, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/distributed/utils.py", line 263, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistBackendError: [2] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer
Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x1543ba428d87 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x589518e (0x1543f612018e in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x360 (0x1543f611a9a0 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x1543f611ace2 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #4: c10d::TCPStore::get(std::string const&) + 0xa1 (0x1543f611bb11 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1543f60d0f81 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1543f60d0f81 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1543f60d0f81 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #8: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xa9 (0x1543bb5a44e9 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #9: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, std::vector<c10::Device, std::allocator<c10::Device> > const&, c10d::OpType, int, bool) + 0x22b (0x1543bb5ab4db in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #10: c10d::ProcessGroupNCCL::allgather(std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > >&, std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllgatherOptions const&) + 0xb5c (0x1543bb5c18dc in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0x583a31d (0x1543f60c531d in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x5844218 (0x1543f60cf218 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x4e893cc (0x1543f57143cc in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x1a08a88 (0x1543f2293a88 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x584ba33 (0x1543f60d6a33 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x5856e1f (0x1543f60e1e1f in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #17: c10d::verify_params_across_processes(c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::optional<std::weak_ptr<c10d::Logger> > const&) + 0x26f (0x1543f614848f in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0xc62071 (0x15440894b071 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #19: <unknown function> + 0x416284 (0x1544080ff284 in /home/mmahdid/.conda/envs/fastclip/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #20: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x528767]
frame #21: _PyObject_MakeTpCall + 0x26c (0x5041ac in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #22: _PyEval_EvalFrameDefault + 0x6a7 (0x5116e7 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #23: _PyFunction_Vectorcall + 0x173 (0x538cc3 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #24: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5400d2]
frame #25: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5045ac]
frame #26: PyObject_Call + 0xbd (0x542b7d in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #27: _PyEval_EvalFrameDefault + 0x47a9 (0x5157e9 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #28: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5cbeda]
frame #29: PyEval_EvalCode + 0x9f (0x5cb5af in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #30: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5ec6a7]
frame #31: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5e8240]
frame #32: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5fd192]
frame #33: _PyRun_SimpleFileObject + 0x19f (0x5fc55f in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #34: _PyRun_AnyFileObject + 0x43 (0x5fc283 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #35: Py_RunMain + 0x2ee (0x5f6efe in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #36: Py_BytesMain + 0x39 (0x5bbc79 in /home/mmahdid/.conda/envs/fastclip/bin//python)
frame #37: __libc_start_main + 0xe5 (0x15441aa5fd85 in /lib64/libc.so.6)
frame #38: /home/mmahdid/.conda/envs/fastclip/bin//python() [0x5bbac3]
. This may indicate a possible application crash on rank 0 or a network set up issue.
[rank2]:[2024-07-09 10:12:38,229] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[rank2]:[2024-07-09 10:12:38,229] torch._dynamo.utils: [INFO] Function, Runtimes (s)
srun: error: gcn152: task 1: Exited with exit code 1
srun: Terminating StepId=6921391.0
slurmstepd: error: *** STEP 6921391.0 ON gcn152 CANCELLED AT 2024-07-09T10:12:38 ***
srun: error: gcn152: task 2: Exited with exit code 1
srun: error: gcn152: task 3: Terminated
srun: Force Terminated StepId=6921391.0
```

Could you please let me know what can be the source of the error?

**Comment by xywei00** [comment]
Hi, do you mind sharing the full output? This looks like rank 0 exits for some reason, and it causes others to hang.

**Comment by mmderakhshani** [comment]
Sure, here it is. 

```
2024-07-10,09:39:27 | INFO | Running in distributed mode with multiple processes. Device: cuda:3.Process (global: 3, local 3), total 4.
2024-07-10,09:39:27 | INFO | Loaded RN50 model config.
[rank3]: Traceback (most recent call last):
[rank3]:   File "/gpfs/home2/mmahdid/fast_clip/src/training/main.py", line 611, in <module>
[rank3]:     main(sys.argv[1:])
[rank3]:   File "/gpfs/home2/mmahdid/fast_clip/src/training/main.py", line 304, in main
[rank3]:     model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[device], **ddp_args)
[rank3]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 798, in __init__
[rank3]:     _verify_param_shape_across_processes(self.process_group, parameters)
[rank3]:   File "/home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/distributed/utils.py", line 269, in _verify_param_shape_across_processes
[rank3]:     return dist._verify_params_across_processes(process_group, tensors, logger)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]: torch.distributed.DistBackendError: [3] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer
[rank3]: Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:672 (most recent call first):
[rank3]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x154057169897 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libc10.so)
[rank3]: frame #1: <unknown function> + 0x5b3a23e (0x154090c8723e in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x2c7 (0x154090c81c87 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #3: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x154090c81f82 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #4: c10d::TCPStore::get(std::string const&) + 0xa1 (0x154090c82fd1 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x154090c37371 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x154090c37371 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x154090c37371 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #8: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xa9 (0x1540584446d9 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #9: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0xc50 (0x15405844bb60 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #10: c10d::ProcessGroupNCCL::allgather(std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > >&, std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllgatherOptions const&) + 0x857 (0x15405845e287 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #11: <unknown function> + 0x5ade1dd (0x154090c2b1dd in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #12: <unknown function> + 0x5ae7ea2 (0x154090c34ea2 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #13: <unknown function> + 0x5124446 (0x154090271446 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #14: <unknown function> + 0x1acf4b8 (0x15408cc1c4b8 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #15: <unknown function> + 0x5aeff43 (0x154090c3cf43 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #16: <unknown function> + 0x5afb73f (0x154090c4873f in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #17: c10d::verify_params_across_processes(c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::optional<std::weak_ptr<c10d::Logger> > const&) + 0x26d (0x154090caf1ad in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #18: <unknown function> + 0xce9c61 (0x1540a37edc61 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
[rank3]: frame #19: <unknown function> + 0x47ef94 (0x1540a2f82f94 in /home/mmahdid/.conda/envs/fastclipbetter/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
[rank3]: frame #20: /home/mmahdid/.conda/envs/fastclipbetter/bin/python() [0x528767]
[rank3]: frame #21: _PyObject_MakeTpCall + 0x26c (0x5041ac in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #22: _PyEval_EvalFrameDefault + 0x6a7 (0x5116e7 in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #23: _PyFunction_Vectorcall + 0x173 (0x538cc3 in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #24: /home/mmahdid/.conda/envs/fastclipbetter/bin/python() [0x5400d2]
[rank3]: frame #25: /home/mmahdid/.conda/envs/fastclipbetter/bin/python() [0x5045ac]
[rank3]: frame #26: PyObject_Call + 0xbd (0x542b7d in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #27: _PyEval_EvalFrameDefault + 0x47a9 (0x5157e9 in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #28: /home/mmahdid/.conda/envs/fastclipbetter/bin/python() [0x5cbeda]
[rank3]: frame #29: PyEval_EvalCode + 0x9f (0x5cb5af in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #30: /home/mmahdid/.conda/envs/fastclipbetter/bin/python() [0x5ec6a7]
[rank3]: frame #31: /home/mmahdid/.conda/envs/fastclipbetter/bin/python() [0x5e8240]
[rank3]: frame #32: /home/mmahdid/.conda/envs/fastclipbetter/bin/python() [0x5fd192]
[rank3]: frame #33: _PyRun_SimpleFileObject + 0x19f (0x5fc55f in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #34: _PyRun_AnyFileObject + 0x43 (0x5fc283 in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #35: Py_RunMain + 0x2ee (0x5f6efe in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #36: Py_BytesMain + 0x39 (0x5bbc79 in /home/mmahdid/.conda/envs/fastclipbetter/bin/python)
[rank3]: frame #37: __libc_start_main + 0xe5 (0x1540b5934d85 in /lib64/libc.so.6)
[rank3]: frame #38: /home/mmahdid/.conda/envs/fastclipbetter/bin/python() [0x5bbac3]
[rank3]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank3]:I0710 09:39:28.713000 23367684469248 torch/_dynamo/utils.py:320] TorchDynamo compilation metrics:
[rank3]:I0710 09:39:28.713000 23367684469248 torch/_dynamo/utils.py:320] Function, Runtimes (s)
2024-07-10,09:39:28 | INFO | Running in distributed mode with multiple processes. Device: cuda:2.Process (global: 2, local 2), total 4.
2024-07-10,09:39:28 | INFO | Running in distributed mode with multiple processes. Device: cuda:1.Process (global: 1, local 1), total 4.
2024-07-10,09:39:28 | INFO | Loaded RN50 model config.
2024-07-10,09:39:28 | INFO | Loaded RN50 model config.
srun: error: gcn153: task 3: Exited with exit code 1
srun: Terminating StepId=6932608.0
slurmstepd: error: *** STEP 6932608.0 ON gcn153 CANCELLED AT 2024-07-10T09:39:29 ***
srun: error: gcn153: task 2: Terminated
srun: error: gcn153: task 1: Terminated
srun: Force Terminated StepId=6932608.0

```

**Comment by xywei00** [comment]
It seems rank 0 did not encounter any error but still exited. In my experience, this is related to the `Experiment already exists` error. What is the content of the other output file (`%x_%j_logs.log`)?

**Comment by mmderakhshani** [comment]
I found the problem. "Experiments already exist" refers to the `logs` folder that was created by the script. I removed it and now I do not have the same problem anymore. 

One more thing I have noticed is that I can see the following two imports in the data.py file.
```
try:
    from libauc.datasets.webdataset import WebDataset
except ModuleNotFoundError:
    from webdata import WebDataset
```
However I am getting this error:
```
ModuleNotFoundError: No module named 'libauc.datasets.webdataset'
```

what is your libauc version?

**Comment by xywei00** [comment]
This should work for any version of libauc since the `ModuleNotFoundError` will be handled by the except clause. Could you share the command that triggers the error and its full output?

**Comment by mmderakhshani** [comment]
I resolved the problem. May I ask you to share your Slurm scripts for reproducing the results for CC12M and LAION400M?

**Comment by xywei00** [comment]
Please see the updated readme.
